apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jlaai40pg-python 
  janus-idp.io/tekton: jlaai40pg-python
  backstage.io/kubernetes-id: jlaai40pg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jlaai40pg-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml