apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jlaai40pg-python
  janus-idp.io/tekton: jlaai40pg-python
  backstage.io/kubernetes-id: jlaai40pg-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jlaai40pg-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
